spring:
  config:
    activate:
      on-profile: prod

  thymeleaf:
    cache: true

#  datasource:
#    url: ${DB_URL}
#    username: ${DB_USERNAME}
#    password: ${DB_PASSWORD}
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    hikari:
#      maximum-pool-size: 10
#      minimum-idle: 5
#
#  jpa:
#    database-platform: org.hibernate.dialect.MySQLDialect
#    hibernate:
#      ddl-auto: update
#    show-sql: false

jwt:
  secret:
    key: ${JWT_SECRET}
  token-validity-in-seconds: ${JWT_VALIDITY}
  refresh-token-validity-in-seconds: ${JWT_REFRESH_VALIDITY}

#portone:
#  api:
#    secret: ${PORTONE_API_SECRET}
#  store:
#    id: ${PORTONE_STORE_ID}
#  channel:
#    toss: ${PORTONE_CHANNEL_TOSS}
#    toss-billing: ${PORTONE_CHANNEL_TOSS_BILLING}

logging:
  level:
    com.example.a3sproject: info
    org.springframework.security: info
